apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::823914818591:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-2904SXDBVU9F
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::823914818591:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-04T21:10:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1450"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 210b900d-21ae-403d-acd7-eaacfc933a76
