apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::823914818591:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::823914818591:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-S1RP3YRKB1KR
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-02T09:04:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1338"
  uid: 733bfa74-8ea4-454e-a04c-79a6fbb331fe
